version: '3.8'
services:
  web:
    image: web
    restart: unless-stopped
    build: ./client/
    ports:
      - '3000:3000'
    networks:
      - lenda-app
  api:
    image: api
    restart: unless-stopped
    build: ./server/
    ports:
      - '5000:5000'
    networks:
      - lenda-app

networks:
  lenda-app:
    driver: bridge
